# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - dawairx-app

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to container registry
        uses: docker/login-action@v2
        with:
          registry: dawairxregistry.azurecr.io/
          username: ${{ secrets.AZUREAPPSERVICE_CONTAINERUSERNAME_E625B8FC1BD446E3A799BB5A73529B77 }}
          password: ${{ secrets.AZUREAPPSERVICE_CONTAINERPASSWORD_053AAE0CD71B434FAFA8F9698430A38C }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: dawairxregistry.azurecr.io/${{ secrets.AZUREAPPSERVICE_CONTAINERUSERNAME_E625B8FC1BD446E3A799BB5A73529B77 }}/dawairx:${{ github.sha }}
          file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    needs: build
    
    steps:
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_D774DC31B2444E319A2D49E53614127F }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_373C7D866F8E4C29B3CF46AA30355A23 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_9DE0B8F59F7948C68A91CA0C404007EB }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'dawairx-app'
          slot-name: 'Production'
          images: 'dawairxregistry.azurecr.io/${{ secrets.AZUREAPPSERVICE_CONTAINERUSERNAME_E625B8FC1BD446E3A799BB5A73529B77 }}/dawairx:${{ github.sha }}'
          